[railway]
  builder = "nixpacks"
  buildCommand = "npm ci --omit=dev && cd client && npm ci --omit=dev && npm run build"
  startCommand = "npm run start"

[nodejs]
  version = "20"

[railway.variable]
  NODE_ENV = "production"
  DATABASE_URL = "postgresql://postgres.cpdrclazmvboenhlsccf:Gmc190494mcv@aws-1-us-west-2.pooler.supabase.com:6543/postgres"