[railway]
  builder = "nixpacks"
  buildCommand = "npm ci --omit=dev && cd client && npm ci --omit=dev && npm run build"
  startCommand = "npm run start"

[nodejs]
  version = "20"

[railway.persistence]
  data = { mount = "/data", readonly = false }